import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/providers/ThemeProvider';
import { ClerkProvider, ClerkLoaded, ClerkLoading } from '@clerk/nextjs';
import ModalContext from '@/context/ModalContext';

const font = Open_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: { icon: '/next.svg' },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={font.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <ModalContext>{children}</ModalContext>
            {/* <ClerkLoading>
              <div className="flex justify-center text-2xl font-bold items-center w-screen h-screen ">
                <p className="animation-scale">Loading ...</p>
              </div>
            </ClerkLoading> */}
            {/* <ClerkLoaded> */}

            {/* </ClerkLoaded> */}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
